onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma

overrides:
  diff@<8.0.3: '>=8.0.3'
  hono@<4.11.4: '>=4.11.4'
  tmp@<=0.2.3: '>=0.2.4'
  undici@<6.23.0: '>=6.23.0'
