onlyBuiltDependencies:
  - core-js
  - esbuild
  - unrs-resolver

overrides:
  pug-code-gen@<=3.0.2: '>=3.0.3'
  pug@<3.0.1: '>=3.0.1'
  pug@<=3.0.2: '>=3.0.3'
  tmp@<=0.2.3: '>=0.2.4'
  vue-template-compiler@>=2.0.0 <3.0.0: '>=3.0.0'
