/**
 * Data Transfer Object for OAuth 2.0 authorization requests.
 *
 * This interface represents the parameters required for initiating an OAuth 2.0
 * authorization flow with PKCE (Proof Key for Code Exchange) support.
 *
 * @interface AuthorizeRequestDto
 *
 * @property {string} client_id - The unique identifier of the OAuth client application
 * @property {string} response_type - The type of response expected (e.g., 'code' for authorization code flow)
 * @property {string} redirect_uri - The URI to redirect the user after authorization
 * @property {string} code_challenge - The PKCE code challenge derived from the code verifier
 * @property {'S256' | 'plain'} code_challenge_method - The method used to generate the code challenge (S256 for SHA-256 hashing or plain)
 * @property {string} [scope] - Optional. Space-delimited list of requested scopes
 * @property {string} [state] - Optional. Opaque value used to maintain state between request and callback
 *
 * @see {@link https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1 | OAuth 2.0 Authorization Request}
 * @see {@link https://datatracker.ietf.org/doc/html/rfc7636 | PKCE RFC 7636}
 */

export interface AuthorizeRequestDto {
  client_id: string;
  response_type: string;
  redirect_uri: string;
  code_challenge: string;
  code_challenge_method: 'S256' | 'plain';
  scope?: string | undefined;
  state?: string | undefined;
}

/**
 * Data Transfer Object for OAuth2 authorization response.
 *
 * @remarks
 * This interface represents the successful response from an OAuth2 authorization endpoint,
 * containing the authorization code and optional state parameter.
 *
 * @property code - The authorization code generated by the authorization server
 * @property state - Optional state parameter that should match the state sent in the authorization request
 *
 * @see {@link https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2 | RFC 6749 Section 4.1.2}
 */

export interface AuthorizeResponseDto {
  code: string;
  state?: string | undefined;
}
