/**
 * Data Transfer Object representing the OAuth2 authorization response.
 *
 * This interface defines the structure of the response returned after a successful
 * authorization request in the OAuth2 flow.
 *
 * @interface AuthResponseDto
 *
 * @property {string} code - The authorization code generated by the authorization server.
 * This code is exchanged for an access token in the token endpoint.
 *
 * @property {string | undefined} [state] - An optional opaque value used to maintain state
 * between the request and callback. This parameter should be used to prevent CSRF attacks
 * by verifying it matches the state sent in the authorization request.
 */

export interface AuthResponseDto {
	code: string;
	state?: string | undefined;
}
