name: 📚 Generate Documentation

on:
  push: # ✅ Deploy en push a main
    branches: [main]
  pull_request: # ✅ Build en PRs (sin deploy)
    branches: [main]

env:
  NODE_VERSION: '22.18.0'

jobs:
  docs:
    name: 📖 Build Documentation
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 💾 Cache node_modules
        uses: actions/cache/save@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: 🏗️ Generate documentation
        run: pnpm run docs:ci

      - name: 📊 Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: 🚀 Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4

  # Job para verificar links (opcional)
  verify:
    name: 🔍 Verify Documentation
    runs-on: ubuntu-latest
    needs: docs
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 🌐 Check documentation URL
        run: |
          echo "📖 Documentation deployed to:"
          echo "🔗 https://jruvalcabafsd.github.io/ByteBerry-oauth2/"
